### ISSUE TITLE
when I use this , something happend

### ISSUE THREAD

**Issue by VALKERIZ** [givingwu/vue-virtualized-table#11]
![image](https://user-images.githubusercontent.com/34742271/92363118-9b4ebf00-f123-11ea-8ddd-a2f8c0cf46d6.png)
I had tried to install the jsx loader and did adaptation but it didn`t work.

**Comment by givingwu** [comment]
I know what happened, may this [link](https://cli.vuejs.org/config/#transpiledependencies) can help you.
