### ISSUE TITLE
当添加自动换行后，滚动条快速滚动会白屏或者卡顿

### ISSUE THREAD

**Issue by zliuxia** [givingwu/vue-virtualized-table#19]
当添加自动换行后，滚动条快速滚动会白屏或者卡顿，有没有什么好的解决办法

**Comment by zliuxia** [comment]
![image](https://user-images.githubusercontent.com/18710626/139607981-b57c542d-f194-42bb-baee-60ec636544b2.png)
设置了rowHeight

**Comment by givingwu** [comment]
请贴上代码，或者创建一个可重现仓库。

**Comment by zliuxia** [comment]
[lx.zip](https://github.com/givingwu/vue-virtualized-table/files/7480412/lx.zip)

**Comment by givingwu** [comment]
此问题的原因是滚动的数据内容高度不固定导致。

1. 目前 rowHeight 并不支持动态高度。
