### ISSUE TITLE
父级收起展开会影响子级的收起展开

### ISSUE THREAD

**Issue by zliuxia** [givingwu/vue-virtualized-table#21]

**Comment by givingwu** [comment]
PR is welcome, Or you can comment on a gif.

**Comment by zliuxia** [comment]
![2021-12-08-09-25-35](https://user-images.githubusercontent.com/18710626/146317219-117ec4ad-ca5c-48da-877b-25995646a2a4.gif)

**Comment by givingwu** [comment]
我们是故意这样设计的，原因是因为在虚拟滚动的组件中，展开和收起的本质上是当前的一维数组。当收起上一级之后，其所有子集将不再参与 可视区域数据 的计算。最关键的问题是，设计之初，为了简便，没有考虑到缓存子级的展开/收起状态。
