### ISSUE TITLE
Vue 3 compatibility and use with Ant Design v2

### ISSUE THREAD

**Issue by cihadturhan** [givingwu/vue-virtualized-table#23]
Hi,
I'd like to use this with ant design. Is there a way to use ant design classes (such as `.ant-table-column-title`, `.ant-table-header-column`) because we're modifying ant design less variables and would like to see same theme applies this plugin too.

Another question, will there be vue3 compatibility?

**Comment by givingwu** [comment]
The 1st question:

It could be used with Ant Design v4, maybe cannot work with v2. I never do any test for that, but there is something different between v2 & v4 as the following:

1. The fixed left/right table & fixed top header will render a new table container in Ant Design V2/3, but not v4 cuz it uses a new CSS3 property `position: sticky`  to fix the `td` which should be fixed.
2. So their class name must be different as well.

The 2nd question:
Vue3 compatibility is still in planning, cause our company has not upgraded it now. We think Vue3 is more complex for our backend developers, they only know how to write Vue like HTML + JSON option API, not JSX/TSX with Reactive/Ref, etc.

That's all, thanks for your questions.
