### ISSUE TITLE
关闭默认展开 图标错误

### ISSUE THREAD

**Issue by 1031531798** [givingwu/vue-virtualized-table#24]
``defaultExpandAllRows = false``

设置取消默认展开后 图标不正确  并且点击后是不会展开

![image](https://user-images.githubusercontent.com/52456589/202109390-9a088b00-f502-40eb-938a-4a153b4fe1c1.png)

**Comment by 1031531798** [comment]
我自己做下了修改 已经解决了这个问题 我想上传下代码 你看看是否可行？

**Comment by givingwu** [comment]
可以的，感谢

**Comment by givingwu** [comment]
请提 PR
